# Generated by Django 4.2.7 on 2023-12-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='wikientry',
            name='author',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wikientry',
            name='comments',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wikientry',
            name='tags',
            field=models.TextField(default=''),
        ),
        migrations.AddField(
            model_name='wikientry',
            name='views',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='wikientry',
            name='content',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='wikientry',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
