# Generated by Django 4.2.7 on 2023-12-28 00:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('wiki', '0002_wikientry_author_wikientry_comments_wikientry_tags_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='wikientry',
            name='comments',
        ),
        migrations.RemoveField(
            model_name='wikientry',
            name='views',
        ),
    ]
