# Generated by Django 4.1.7 on 2023-03-27 17:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Marker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('icon', models.CharField(max_length=50)),
                ('mplsNetwork', models.BooleanField()),
                ('routerIp', models.CharField(blank=True, max_length=20)),
            ],
        ),
    ]
