# Generated by Django 4.2.1 on 2023-05-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Markers',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('lat', models.DecimalField(decimal_places=6, max_digits=9)),
                ('lng', models.DecimalField(decimal_places=6, max_digits=9)),
                ('icon', models.CharField(max_length=50)),
                ('mplsNetwork', models.BooleanField()),
                ('routerIp', models.CharField(blank=True, max_length=20)),
            ],
        ),
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('lng', models.CharField(max_length=100)),
                ('wanIp', models.CharField(max_length=100)),
                ('wan2Ip', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('opHr', models.CharField(max_length=100)),
                ('cleanliness_rating', models.IntegerField(blank=True)),
                ('difficulty_rating', models.IntegerField(blank=True)),
                ('rack_grounding', models.BooleanField(blank=True)),
                ('idf_mdf_door_locked', models.BooleanField(blank=True)),
                ('air_conditioning_functioning', models.BooleanField(blank=True)),
                ('ups_functioning', models.BooleanField(blank=True)),
                ('ups_logic_monitor_setup', models.BooleanField(blank=True)),
                ('temperature_humidity_sensors_setup', models.BooleanField(blank=True)),
                ('idf_mdf_cable_managed', models.BooleanField(blank=True)),
                ('appropriate_size_cables', models.BooleanField(blank=True)),
                ('idf_mdf_clean_clear', models.BooleanField(blank=True)),
                ('devices_labeled', models.BooleanField(blank=True)),
                ('fiber_undamaged', models.BooleanField(blank=True)),
                ('devices_dual_power', models.BooleanField(blank=True)),
                ('trashcan', models.BooleanField(blank=True)),
            ],
        ),
        migrations.DeleteModel(
            name='Marker',
        ),
    ]
