# Generated by Django 4.2.1 on 2023-05-26 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0002_markers_site_delete_marker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='air_conditioning_functioning',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='appropriate_size_cables',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='cleanliness_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='devices_dual_power',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='devices_labeled',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='difficulty_rating',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='fiber_undamaged',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='idf_mdf_cable_managed',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='idf_mdf_clean_clear',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='idf_mdf_door_locked',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='rack_grounding',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='temperature_humidity_sensors_setup',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='trashcan',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='ups_functioning',
            field=models.BooleanField(null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='ups_logic_monitor_setup',
            field=models.BooleanField(null=True),
        ),
    ]
