# Generated by Django 4.2.1 on 2023-06-19 23:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0003_alter_site_air_conditioning_functioning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='comments',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
