# Generated by Django 4.2.1 on 2023-07-17 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0004_site_comments'),
    ]

    operations = [
        migrations.CreateModel(
            name='Device_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('serial', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('url', models.CharField(max_length=1000)),
                ('networkId', models.CharField(max_length=100)),
                ('name', models.CharField(max_length=100)),
                ('model', models.CharField(max_length=100)),
                ('firmware', models.CharField(max_length=100)),
                ('site', models.CharField(max_length=100)),
                ('productType', models.CharField(max_length=100)),
                ('networkName', models.CharField(max_length=100)),
            ],
        ),
    ]
