# Generated by Django 4.2.1 on 2023-07-17 16:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0005_device_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='device_info',
            name='site',
        ),
    ]
