# Generated by Django 4.2.1 on 2023-07-20 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0006_remove_device_info_site'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='networkId',
            field=models.CharField(default='', max_length=100),
        ),
    ]
