# Generated by Django 4.2.1 on 2023-07-20 21:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0007_site_networkid'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='networkName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
