# Generated by Django 4.2.1 on 2023-07-27 22:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0008_site_networkname'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='clients',
            field=models.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='site',
            name='vlans',
            field=models.JSONField(default=dict),
        ),
    ]
