# Generated by Django 4.2.1 on 2023-08-17 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0010_site_available'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='router_sn',
            field=models.CharField(default='', max_length=100),
        ),
    ]
