# Generated by Django 4.2.1 on 2023-09-01 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0011_site_router_sn'),
    ]

    operations = [
        migrations.CreateModel(
            name='Client_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clinet_id', models.CharField(max_length=100)),
                ('mac', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=100)),
                ('ip', models.CharField(max_length=100)),
                ('ip6', models.CharField(max_length=100)),
                ('ip6Local', models.CharField(max_length=100)),
                ('user', models.CharField(max_length=100)),
                ('firstSeen', models.CharField(max_length=100)),
                ('lastSeen', models.CharField(max_length=100)),
                ('manufacturer', models.CharField(max_length=100)),
                ('os', models.CharField(max_length=100)),
                ('deviceTypePrediction', models.CharField(max_length=100)),
                ('recentDeviceSerial', models.CharField(max_length=100)),
                ('recentDeviceName', models.CharField(max_length=100)),
                ('recentDeviceMac', models.CharField(max_length=100)),
                ('recentDeviceConnection', models.CharField(max_length=100)),
                ('ssid', models.CharField(max_length=100)),
                ('vlan', models.CharField(max_length=100)),
                ('switchport', models.CharField(max_length=100)),
                ('usage', models.JSONField()),
                ('us', models.CharField(max_length=100)),
                ('notes', models.CharField(max_length=100)),
                ('groupPolicy8021x', models.CharField(max_length=100)),
                ('adaptivePolicyGroup', models.CharField(max_length=100)),
                ('smInstalled', models.CharField(max_length=100)),
                ('pskGroup', models.CharField(max_length=100)),
            ],
        ),
    ]
