# Generated by Django 4.2.1 on 2023-09-01 23:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0012_client_info'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_info',
            old_name='us',
            new_name='status',
        ),
    ]
