# Generated by Django 4.2.1 on 2023-09-01 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0013_rename_us_client_info_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='client_info',
            old_name='clinet_id',
            new_name='client_id',
        ),
    ]
