# Generated by Django 4.2.1 on 2023-09-11 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0014_rename_clinet_id_client_info_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='client_info',
            name='ip',
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name='client_info',
            name='mac',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
