# Generated by Django 4.2.1 on 2023-09-11 23:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0015_alter_client_info_ip_alter_client_info_mac'),
    ]

    operations = [
        migrations.AddField(
            model_name='client_info',
            name='network_name',
            field=models.CharField(default='', max_length=100),
        ),
    ]
