# Generated by Django 4.2.1 on 2023-09-12 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0016_client_info_network_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='Org_Info',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_count', models.CharField(default='', max_length=100)),
                ('site_count', models.CharField(default='', max_length=100)),
                ('users', models.JSONField()),
            ],
        ),
    ]
