# Generated by Django 4.2.1 on 2023-11-09 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0017_org_info'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('status', models.CharField(default='pending', max_length=20)),
                ('created_date', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
