# Generated by Django 4.2.7 on 2023-12-28 00:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0019_featurerequest_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='Employee',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first_name', models.CharField(default='', max_length=100)),
                ('last_name', models.CharField(default='', max_length=100)),
                ('display_name', models.CharField(default='', max_length=100)),
                ('mail', models.CharField(default='', max_length=100)),
                ('webex_id', models.CharField(default='')),
                ('azure_id', models.CharField(default='')),
                ('phone_number', models.IntegerField(default='')),
                ('badge_number', models.IntegerField(default='')),
                ('phone_mac', models.IntegerField(default='')),
                ('site', models.CharField(default='')),
                ('title', models.CharField(default='')),
                ('manager', models.CharField(default='')),
                ('hire_date', models.CharField(default='')),
                ('upn', models.CharField(default='')),
                ('givenName', models.CharField(default='')),
            ],
        ),
    ]
