# Generated by Django 4.2.7 on 2023-12-28 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0020_employee'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.IntegerField(default=1),
        ),
    ]
