# Generated by Django 4.2.7 on 2023-12-28 00:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0021_alter_employee_phone_number'),
    ]

    operations = [
        migrations.RenameField(
            model_name='employee',
            old_name='phone_number',
            new_name='phone',
        ),
    ]
