# Generated by Django 4.2.7 on 2023-12-28 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0022_rename_phone_number_employee_phone'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone',
        ),
    ]
