# Generated by Django 4.2.7 on 2023-12-28 00:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0023_remove_employee_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='phone_number',
            field=models.IntegerField(default=1),
        ),
    ]
