# Generated by Django 4.2.7 on 2023-12-28 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0024_employee_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone_number',
            field=models.IntegerField(default=''),
        ),
    ]
