# Generated by Django 4.2.7 on 2023-12-28 00:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0025_alter_employee_phone_number'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employee',
            name='phone_number',
        ),
    ]
