# Generated by Django 4.2.7 on 2023-12-28 00:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0028_alter_employee_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='badge_number',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='employee',
            name='phone_mac',
            field=models.IntegerField(default=0),
        ),
    ]
