# Generated by Django 4.2.7 on 2023-12-28 16:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0029_alter_employee_badge_number_alter_employee_phone_mac'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='azure_id',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='givenName',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='site',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='upn',
            field=models.CharField(null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='webex_id',
            field=models.CharField(null=True),
        ),
    ]
