# Generated by Django 4.2.7 on 2023-12-28 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0030_alter_employee_azure_id_alter_employee_givenname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='mail',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
