# Generated by Django 4.2.7 on 2023-12-28 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0031_alter_employee_mail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='last_name',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
