# Generated by Django 4.2.7 on 2023-12-28 17:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0032_alter_employee_last_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='phone',
            field=models.JSONField(default=dict),
        ),
    ]
