# Generated by Django 4.2.1 on 2024-01-02 21:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0035_alter_employee_badge_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='extension',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='webex_last_act',
            field=models.CharField(null=True),
        ),
        migrations.AddField(
            model_name='employee',
            name='webex_lic',
            field=models.JSONField(default=dict),
        ),
    ]
