# Generated by Django 4.2.1 on 2024-01-03 00:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0036_employee_extension_employee_webex_last_act_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='webex_dev_id',
            field=models.CharField(null=True),
        ),
    ]
