# Generated by Django 4.2.1 on 2024-01-04 17:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0037_employee_webex_dev_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='webexName',
            field=models.CharField(default='', max_length=100),
        ),
    ]
