# Generated by Django 4.2.1 on 2024-01-04 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0038_site_webexname'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='cleanliness_rating',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='comments',
            field=models.CharField(default='', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='difficulty_rating',
            field=models.IntegerField(default='', null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='networkName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='webexName',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
