# Generated by Django 4.2.1 on 2024-01-04 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0039_alter_site_cleanliness_rating_alter_site_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='cleanliness_rating',
            field=models.IntegerField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='comments',
            field=models.CharField(default='Test', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='difficulty_rating',
            field=models.IntegerField(default=1, null=True),
        ),
    ]
