# Generated by Django 4.2.1 on 2024-01-04 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0040_alter_site_cleanliness_rating_alter_site_comments_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='site',
            name='address',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='air_conditioning_functioning',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='appropriate_size_cables',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='available',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='site',
            name='cleanliness_rating',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='clients',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='site',
            name='comments',
            field=models.CharField(blank=True, default='Test', max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='devices_dual_power',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='devices_labeled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='difficulty_rating',
            field=models.IntegerField(blank=True, default=1, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='fiber_undamaged',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='idf_mdf_cable_managed',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='idf_mdf_clean_clear',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='idf_mdf_door_locked',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='lat',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='link',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='lng',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='name',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='networkId',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='networkName',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='opHr',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='rack_grounding',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='router_sn',
            field=models.CharField(blank=True, default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='temperature_humidity_sensors_setup',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='trashcan',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='ups_functioning',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='ups_logic_monitor_setup',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='site',
            name='vlans',
            field=models.JSONField(blank=True, default=dict),
        ),
        migrations.AlterField(
            model_name='site',
            name='wan2Ip',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='wanIp',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='site',
            name='webexName',
            field=models.CharField(blank=True, default='', max_length=100, null=True),
        ),
    ]
