# Generated by Django 4.2.1 on 2024-01-04 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0042_site_webex_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='webex_loc_id',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
