# Generated by Django 4.2.1 on 2024-01-04 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0043_employee_webex_loc_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='webex_model',
            field=models.CharField(default='', max_length=150, null=True),
        ),
    ]
