# Generated by Django 4.2.1 on 2024-03-12 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0044_employee_webex_model'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org_info',
            name='users',
        ),
        migrations.AddField(
            model_name='org_info',
            name='contact_email',
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name='org_info',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='org_info',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AddField(
            model_name='org_info',
            name='industry',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='org_info',
            name='meraki_api_key',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='org_info',
            name='network_device_ips',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='org_info',
            name='org_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='org_info',
            name='organization_address',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='org_info',
            name='organization_logo',
            field=models.ImageField(blank=True, null=True, upload_to='org_logos/'),
        ),
        migrations.AddField(
            model_name='org_info',
            name='updated_at',
            field=models.DateTimeField(auto_now=True, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='azure_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='extension',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='givenName',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='hire_date',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='manager',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='site',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='title',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='upn',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='webex_dev_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='webex_id',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='employee',
            name='webex_last_act',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='org_info',
            name='client_count',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='org_info',
            name='site_count',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
