# Generated by Django 4.2.1 on 2024-03-15 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0045_remove_org_info_users_org_info_contact_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_info',
            name='repo_name',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AlterField(
            model_name='org_info',
            name='organization_address',
            field=models.TextField(blank=True, max_length=200, null=True),
        ),
    ]
