# Generated by Django 4.2.1 on 2024-03-20 04:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0046_org_info_repo_name_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkDevice',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=15)),
                ('model', models.CharField(max_length=100)),
                ('username', models.CharField(max_length=100)),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.AddField(
            model_name='org_info',
            name='ssh_password',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='org_info',
            name='ssh_username',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
