# Generated by Django 4.2.1 on 2024-03-20 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0047_networkdevice_org_info_ssh_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='hostname',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='make',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='serial_number',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='ip_address',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='networkdevice',
            name='model',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
