# Generated by Django 4.2.1 on 2024-03-24 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0048_networkdevice_hostname_networkdevice_make_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_info',
            name='ssh_enable_password',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
