# Generated by Django 4.2.1 on 2024-03-24 03:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0049_org_info_ssh_enable_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='online',
            field=models.BooleanField(default=False),
        ),
    ]
