# Generated by Django 4.2.1 on 2024-03-24 04:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0051_networkdevice_enable_password'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='device_type',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
