# Generated by Django 4.2.1 on 2024-03-26 23:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0052_networkdevice_device_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='firmware_version',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
