# Generated by Django 4.2.1 on 2024-04-03 02:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0053_networkdevice_firmware_version'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='ansible_status',
            field=models.CharField(default='', max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='networkdevice',
            name='image',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
