# Generated by Django 4.2.1 on 2024-04-05 01:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0054_networkdevice_ansible_status_networkdevice_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='RunningConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('config_text', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='running_configs', to='map.networkdevice')),
            ],
            options={
                'db_table': 'running_configs',
                'ordering': ['-created_at'],
            },
        ),
    ]
