# Generated by Django 4.2.1 on 2024-04-04 20:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0055_runningconfig'),
    ]

    operations = [
        migrations.AlterField(
            model_name='runningconfig',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.CreateModel(
            name='NetworkInterface',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('mac_address', models.CharField(max_length=17)),
                ('mtu', models.PositiveIntegerField()),
                ('bandwidth', models.PositiveIntegerField()),
                ('media_type', models.CharField(blank=True, max_length=50, null=True)),
                ('duplex', models.CharField(blank=True, max_length=50, null=True)),
                ('line_protocol', models.CharField(max_length=50)),
                ('oper_status', models.CharField(max_length=50)),
                ('interface_type', models.CharField(max_length=50)),
                ('ipv4_address', models.CharField(blank=True, max_length=50, null=True)),
                ('ipv4_subnet', models.CharField(blank=True, max_length=50, null=True)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interfaces', to='map.networkdevice')),
            ],
        ),
    ]
