# Generated by Django 4.2.1 on 2024-04-04 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0056_alter_runningconfig_created_at_networkinterface'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterface',
            name='mac_address',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
