# Generated by Django 4.2.1 on 2024-04-04 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0057_alter_networkinterface_mac_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkinterface',
            name='interface_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networkinterface',
            name='line_protocol',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='networkinterface',
            name='oper_status',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
