# Generated by Django 4.2.1 on 2024-04-07 15:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0058_alter_networkinterface_interface_type_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='short_name',
            field=models.CharField(blank=True, max_length=17, null=True),
        ),
    ]
