# Generated by Django 4.2.1 on 2024-05-07 14:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0059_networkinterface_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkinterface',
            name='allowed_vlans',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='encapsulation',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='mode',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='native_vlan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='vlan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='networkinterface',
            name='voice_vlan',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
