# Generated by Django 4.2.1 on 2024-05-11 12:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0060_networkinterface_allowed_vlans_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result', models.BooleanField()),
                ('start_time', models.CharField(max_length=200)),
                ('end_time', models.CharField(max_length=200)),
                ('duration', models.CharField(max_length=200)),
                ('name', models.CharField(max_length=100)),
                ('uid', models.CharField(max_length=250)),
                ('device', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='map.networkdevice')),
            ],
        ),
    ]
