# Generated by Django 4.2.1 on 2024-05-13 12:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0063_networktask_task_result'),
    ]

    operations = [
        migrations.AddField(
            model_name='networktask',
            name='task_sent',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
