# Generated by Django 4.2.1 on 2024-05-13 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0064_networktask_task_sent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networktask',
            name='task_sent',
        ),
    ]
