# Generated by Django 4.2.1 on 2024-05-13 13:30

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0065_remove_networktask_task_sent'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networktask',
            options={'ordering': ['-created_at']},
        ),
        migrations.AddField(
            model_name='networktask',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
