# Generated by Django 4.2.1 on 2024-05-14 10:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0066_alter_networktask_options_networktask_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='networktask',
            name='msg',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
