# Generated by Django 4.2.1 on 2024-05-14 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0067_networktask_msg'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkdevice',
            name='statup_config',
            field=models.TextField(default='', null=True),
        ),
    ]
