# Generated by Django 4.2.1 on 2024-05-15 12:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0068_networkdevice_statup_config'),
    ]

    operations = [
        migrations.RenameField(
            model_name='networkdevice',
            old_name='statup_config',
            new_name='startup_config',
        ),
    ]
