# Generated by Django 4.2.1 on 2024-05-19 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0069_rename_statup_config_networkdevice_startup_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_info',
            name='admin_group',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='org_info',
            name='bind_account',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='org_info',
            name='bind_password',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='org_info',
            name='dc_ip_address',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='org_info',
            name='license',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='org_info',
            name='tech_group',
            field=models.CharField(default='', max_length=200),
        ),
        migrations.AddField(
            model_name='org_info',
            name='valid',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='org_info',
            name='valid_time',
            field=models.CharField(default='', max_length=200),
        ),
    ]
