# Generated by Django 4.2.1 on 2024-05-19 20:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0073_alter_user_email_alter_user_first_name_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='ldap',
            new_name='isLdap',
        ),
    ]
