# Generated by Django 4.2.1 on 2024-05-19 20:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0075_profile_alter_featurerequest_user_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_info',
            name='admin_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
