# Generated by Django 4.2.1 on 2024-05-20 16:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0076_org_info_admin_username'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_info',
            name='org_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
