# Generated by Django 4.2.1 on 2024-05-21 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0077_org_info_org_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_info',
            name='is_setup',
            field=models.BooleanField(default=False),
        ),
    ]
