# Generated by Django 4.2.1 on 2024-05-22 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0078_org_info_is_setup'),
    ]

    operations = [
        migrations.AddField(
            model_name='org_info',
            name='free_trail_used',
            field=models.BooleanField(default=False),
        ),
    ]
