# Generated by Django 4.2.1 on 2024-05-22 00:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0079_org_info_free_trail_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_info',
            name='license',
            field=models.CharField(default=None, max_length=200),
        ),
    ]
