# Generated by Django 4.2.1 on 2024-05-22 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0080_alter_org_info_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_info',
            name='license',
            field=models.CharField(default='', max_length=200),
        ),
    ]
