# Generated by Django 4.2.1 on 2024-05-22 01:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0081_alter_org_info_license'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_info',
            name='free_trail_used',
            field=models.CharField(default='', max_length=20),
        ),
    ]
