# Generated by Django 4.2.1 on 2024-05-22 01:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0082_alter_org_info_free_trail_used'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_info',
            name='free_trail_used',
            field=models.BooleanField(default=False),
        ),
    ]
