# Generated by Django 4.2.1 on 2024-05-23 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0084_ldapaccount_networkaccount_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='org_info',
            name='admin_username',
        ),
        migrations.AddField(
            model_name='ldapaccount',
            name='admin_username',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
