# Generated by Django 4.2.1 on 2024-05-23 18:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0085_remove_org_info_admin_username_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='org_info',
            name='license',
            field=models.CharField(default='', max_length=200, null=True),
        ),
    ]
