# Generated by Django 4.2.1 on 2024-05-24 18:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0086_alter_org_info_license'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapaccount',
            name='changed',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='org_info',
            name='license',
            field=models.CharField(default='', max_length=200),
        ),
    ]
