# Generated by Django 4.2.1 on 2024-05-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0087_ldapaccount_changed_alter_org_info_license'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='featurerequest',
            name='created_date',
        ),
        migrations.RemoveField(
            model_name='featurerequest',
            name='description',
        ),
        migrations.RemoveField(
            model_name='featurerequest',
            name='status',
        ),
        migrations.AddField(
            model_name='featurerequest',
            name='uid',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='featurerequest',
            name='title',
            field=models.CharField(default='', max_length=100),
        ),
    ]
