# Generated by Django 4.2.1 on 2024-05-26 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0088_remove_featurerequest_created_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featurerequest',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
