# Generated by Django 4.2.1 on 2024-06-27 17:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0090_licenseserverstatus'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='networkdevice',
            name='enable_password',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='password',
        ),
        migrations.RemoveField(
            model_name='networkdevice',
            name='username',
        ),
    ]
