# Generated by Django 4.2.1 on 2024-07-14 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('map', '0091_remove_networkdevice_enable_password_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='licenseserverstatus',
            name='org_id',
            field=models.CharField(default='', max_length=200),
        ),
    ]
