# Generated by Django 4.2.1 on 2023-05-26 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Site',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('lat', models.CharField(max_length=100)),
                ('lng', models.CharField(max_length=100)),
                ('wanIp', models.CharField(max_length=100)),
                ('wan2Ip', models.CharField(max_length=100)),
                ('link', models.CharField(max_length=100)),
                ('opHr', models.CharField(max_length=100)),
                ('cleanliness_rating', models.IntegerField()),
                ('difficulty_rating', models.IntegerField()),
                ('rack_grounding', models.BooleanField()),
                ('idf_mdf_door_locked', models.BooleanField()),
                ('air_conditioning_functioning', models.BooleanField()),
                ('ups_functioning', models.BooleanField()),
                ('ups_logic_monitor_setup', models.BooleanField()),
                ('temperature_humidity_sensors_setup', models.BooleanField()),
                ('idf_mdf_cable_managed', models.BooleanField()),
                ('appropriate_size_cables', models.BooleanField()),
                ('idf_mdf_clean_clear', models.BooleanField()),
                ('devices_labeled', models.BooleanField()),
                ('fiber_undamaged', models.BooleanField()),
                ('devices_dual_power', models.BooleanField()),
                ('trashcan', models.BooleanField()),
            ],
        ),
    ]
