# Generated by Django 4.2.1 on 2023-06-12 23:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siteInfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='site',
            name='comments',
            field=models.CharField(default='', max_length=1000),
        ),
    ]
