# Generated by Django 4.2.1 on 2023-06-19 23:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('siteInfo', '0002_site_comments'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Site',
        ),
    ]
